[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.3"

[dev-dependencies]
iai = "0.1"

[[bench]]
name = "my_benchmark"
harness = false
